### ISSUE TITLE
no source code

### ISSUE THREAD

**Issue by jmtd** [yuvadm/gpg-vanity#1]
as per subject :)

(particularly of interest would be your "interesting" algorithm)

**Comment by yuvadm** [comment]
I haven't gotten to open sourcing my scripts, but they don't have any novel ideas.

You might want to look at https://github.com/lachesis/scallion though :)

**Comment by jmtd** [comment]
Thanks for the tip - just fyi here's my crude interesting-ness algorithms from the last time I did this
https://gist.github.com/jmtd/f2b0347c0a7cbfba77ac
